site_name: consulo.help
repo_url: https://github.com/consulo/consulo-help.github.io
theme:
  name: material
  favicon: art/icon16.svg
  icon:
    repo: fontawesome/brands/github
  logo: art/icon16.svg
  palette:
    primary: black
  features:
    - navigation.instant
    - navigation.tabs
strict: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Help:
    - Welcome: index.md
  - For Platform:
    - Overview: platform/overview.md
    - Settings/Preferences:
      - General:
        - Keymap: platform/settings/general/keymap.md
      - Platform And Plugins: platform/settings/platform.and.plugins.md
        - Experimental Features: platform/settings/platform.and.plugins/experimental.features.md
        - Update Settings: platform/settings/platform.and.plugins/update.settings.md
    - Keymap:
      - Overview: platform/keymap/overview.md
      - OS:
        - Windows | Linux: platform/keymap/windows_linux.md
        - macOS: platform/keymap/mac.md
  - For Plugins:
    - Unity:
      - Overview: plugins/consulo.unity3d/overview.md
      - Setup: plugins/consulo.unity3d/setup.md
      - Debugging: plugins/consulo.unity3d/debugging.md
      - Using Consulo as Editor inside Unity: plugins/consulo.unity3d/using_consulo_as_external_editor.md
