site_name: consulo.help
repo_url: https://github.com/consulo/consulo-help.github.io
theme:
  name: material
  favicon: art/icon16.svg
  icon:
    repo: fontawesome/brands/github
  logo: art/icon16.svg
  palette:
    primary: black
  features:
    - navigation.instant
    - navigation.tabs
strict: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Help:
    - Welcome: index.md
  - For Platform:
    - Overview: platform/overview.md
    - Settings/Preferences:
      - General:
        - Keymap: platform/settings/general/keymap.md
      - External Services: platform/settings/external_services.md
      - Platform and Plugins:
        - Overview: platform/settings/platform_and_plugins/overview.md
        - Experimental Features: platform/settings/platform_and_plugins/experimental_features.md
        - Update Settings: platform/settings/platform_and_plugins/update_settings.md
      - SDKs/Bundles/Tools: platform/settings/sdks_bundles_tools.md
    - Keymap:
      - Overview: platform/keymap/overview.md
      - OS:
        - Windows | Linux: platform/keymap/windows_linux.md
        - macOS: platform/keymap/mac.md
  - For Plugins:
    - Unity:
      - Overview: plugins/consulo.unity3d/overview.md
      - Setup: plugins/consulo.unity3d/setup.md
      - Debugging: plugins/consulo.unity3d/debugging.md
      - Using Consulo as Editor inside Unity: plugins/consulo.unity3d/using_consulo_as_external_editor.md
plugins:
    - redirects:
        redirect_maps:
            'platform/preferences/general/keymap.md': 'platform/settings/general/keymap.md'
            'platform/update_channels.md': 'platform/settings/platform_and_plugins/update_settings.md'

